// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkService.Models;

namespace ParkService.Migrations
{
    [DbContext(typeof(ParkContext))]
    [Migration("20200821220824_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkService.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Crater Lake",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Yoakam Point",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Long Beach",
                            State = "Washington"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Big Bend",
                            State = "Texas"
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Death Valley",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 6,
                            Name = "Everglade",
                            State = "Florida"
                        },
                        new
                        {
                            ParkId = 7,
                            Name = "Gateway Arch",
                            State = "Missouri"
                        },
                        new
                        {
                            ParkId = 8,
                            Name = "Glacier Park",
                            State = "Montana"
                        },
                        new
                        {
                            ParkId = 9,
                            Name = "Grand Teton",
                            State = "Arizona"
                        },
                        new
                        {
                            ParkId = 10,
                            Name = "Great Basin",
                            State = "Nevada"
                        },
                        new
                        {
                            ParkId = 11,
                            Name = "Great Smoky Mountains",
                            State = "North Carolina"
                        },
                        new
                        {
                            ParkId = 12,
                            Name = "Volcano Park",
                            State = "Hawaii"
                        },
                        new
                        {
                            ParkId = 13,
                            Name = "Isla Royale",
                            State = "Michigan"
                        },
                        new
                        {
                            ParkId = 14,
                            Name = "Joshua Tree",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 15,
                            Name = "Kobuk Valley",
                            State = "Alaska"
                        },
                        new
                        {
                            ParkId = 16,
                            Name = "Mammoth Cave",
                            State = "Kentucky"
                        },
                        new
                        {
                            ParkId = 17,
                            Name = "Mesa Verde",
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 18,
                            Name = "Mount Rainier",
                            State = "Washington"
                        },
                        new
                        {
                            ParkId = 19,
                            Name = "Petrified Forest",
                            State = "Arizona"
                        },
                        new
                        {
                            ParkId = 20,
                            Name = "Pinnacles",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 21,
                            Name = "Theodore Roosevelt Park",
                            State = "North Dakota"
                        },
                        new
                        {
                            ParkId = 22,
                            Name = "Voyageurs",
                            State = "Minnesota"
                        },
                        new
                        {
                            ParkId = 23,
                            Name = "White Sands",
                            State = "New Mexico"
                        },
                        new
                        {
                            ParkId = 24,
                            Name = "Wind Cave",
                            State = "South Dakota"
                        },
                        new
                        {
                            ParkId = 25,
                            Name = "Yellowstone",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 26,
                            Name = "Yosemite",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 27,
                            Name = "Zion",
                            State = "Utah"
                        });
                });

            modelBuilder.Entity("ParkService.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
